### ISSUE TITLE
Cannot find name 'HeadersDatasource'

### ISSUE THREAD

**Issue by sangu0009** [juicycleff/nestjs-graphql-gateway#1]
`import { Module } from '@nestjs/common';
import { GraphqlDistributedGatewayModule } from 'nestjs-graphql-gateway';
import { AppController } from './app.controller';
import { AppService } from './app.service';

@Module({
  imports: [
    GraphqlDistributedGatewayModule.forRoot({
      subscriptions: false,
      path: '/graphql',
      context: context => context,
      serviceList: [
        { name: 'reviews', url: 'http://localhost:3001/graphql' },
        { name: 'accounts', url: 'http://localhost:3002/graphql' },
        // more services
      ],
      buildService({ url }) {
        return new HeadersDatasource({ url });
      },
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}

`

**Comment by juicycleff** [comment]
Hey @sangu0009 You can check out my boilerplate to see it https://github.com/juicycleff/ultimate-backend, but between, here is a snippet.

```Typescript

import { RemoteGraphQLDataSource } from '@apollo/gateway';
import * as setCookie from 'set-cookie-parser';

export class HeadersDatasource extends RemoteGraphQLDataSource {
  willSendRequest({ request, context }) {

    if (context.req) {
      if (context.req.headers) {
        const ctxHeaders = context.req.headers;

        for (const key in ctxHeaders) {
          if (ctxHeaders.hasOwnProperty(key)) {
            request.http.headers.set(key, ctxHeaders[key]);
          }
        }
      }
    }
  }

  async didReceiveResponse(response, request, context) {
    const body = await super.didReceiveResponse(response, request, context);

    if (context.res) {
      const cookies = setCookie.parse(response.headers.get('Set-Cookie'), {
        decodeValues: false,
        map: true,
      });
    }
    return body;
  }
}

```
