### ISSUE TITLE
Why is yarn required?

### ISSUE THREAD

**Issue by alanjhonnes** [juicycleff/nestjs-graphql-gateway#3]
I can't install this library on an enterprise project because of the preinstall script checking for yarn, and we can't use yarn on our CI workflows. Can that hook be dropped or is there a specific reason for it?

**Comment by juicycleff** [comment]
@alanjhonnes it's not required I will make a fix if you've not already moved

**Comment by alanjhonnes** [comment]
Hi @juicycleff , thanks for getting back. I've moved on to the PR for federation support on nestjs/graphql with schema-first, but mostly because I was trying to use it in code-first way with type-graph and found some issues with nestjs not working nicely with type-graphql. 

I imagine that yarn hook is something default at your company/projects, but consider removing that for your open-source projects to facilitate adoption, you have some great packages.

**Comment by juicycleff** [comment]
@alanjhonnes sure no problem. I am also happy for the support of schema first with the gateway in nestjs officially. This package will be deprecated soon
